
language: node_js
node_js: node

deploy: 
  app: murmuring-wildwood-23659
  provider: heroku
  api_key:
    secure: EdNEV6mbXUBpJSNXx403nFSP1OnCNlY9VK5oZIJIyfy+sCjFqMdEuJFvLcEp1GHmMN8fSafbYRR7aof0bYo9244bk4vqIZGpXB8YbCtb6QJBmpaP4DaMKbZIWbeMIirjKeq4DeWwtObv1mSiTie8bZaYy0BZRyZtNRXvhmCoBmlXSZDDLZtQF6MLWb9p/OUZ8FY/obrfyrS559p7sLBkWlWz2j/lXIjFWTLJ/B8xsdmpaLj+4KIheWYdQ0QWnpjJRmTp7m7lN3UeBcEYThQsY5BBgrUf7127GFCCn+xRhEwpMos3uSudpfYlHmw0J3PqH/WfrgS8PxdIk52rmoKMRLElKX8BvgcggX83LG01NCRqrjqHdQZ9T9G5oN/erdXuYsBA6IePTGlzHkJhElL0ZsgHVJwqC5lcVzYHYn1vD1/7xK3mNDOHj0q3kZi0R5hPd1S4zYKYFjUjIpse8ZSL65bHJFRwPb5PY2HWAJM+r4GFRNmhOB69YIjlRtK4QTBe7mmLvSApYaxJN4kTvcCT1Oll4dGzrvSHfuAbpn+h0jLG5vpAgwoHyUr2GDhwbEihttyIM+L9du2g7pALSU+JaNpr/yKB5LbRxfITQfkjhDhZ+7hha3HRtAdt6o3oJupz81DP06cT6DDIqHlh562G7FZh9UGMvvNYQjovnl7xPRc=
  on:
    repo: LeCatalyser/node-shopping-list-integration-tests
    branch: test-for-recipes
